export const ENCRYPT_TEXT = "ENCRYPT_TEXT";
export const STORE_RANDOM_KEY = "STORE_RANDOM_KEY";
export const STRING_NOT_VALID = "STRING_NOT_VALID";
export const NO_MORE_NUMBER = "NO_MORE_NUMBER";
export const SHOW_INFO = "SHOW_INFO";
